### ISSUE TITLE
Fix Unsafe Command Run?

### ISSUE THREAD

**Issue by ekristen** [oplik0/openPGP-action#12]
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by oplik0** [comment]
I apologize for the very long delay, and it is entirely my fault as for some unimaginable reason it seems I disabled notifications for this repository and as a result just kind of forgot about it.

Updated things properly now, and released the changes. Also turned on notifications now, so I'll be able to merge dependabot PRs. Will also try to work on the code a little bit, to at least make it more readable and easier to follow.
